In [4]:
import tensorflow as tf
import numpy as np

In [7]:
# mnist 기초 / tensorFlow tutorial
mnist = tf.keras.datasets.mnist # mnist : 손으로 쓴 숫자들의 이미지 데이터셋
(x_train, y_train), (x_test, y_test) = mnist.load_data() '''
                                                         train_set 과 test_set을 나누는 이유 : 과적합을 방지하기 위해서
                                                         과적합 :학습 데이터로는 예측을 잘하지만, 실제 데이터로는 그렇지 못한 상태
                                                         '''
x_train, x_test = x_train / 255.0, x_test / 255.0 # 이미지 픽셀 값의 범위가 255, 255 나누어 값의 범위를 0~1로 조정

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
x_train shape: (60000, 28, 28)


In [20]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)), # 2차원 배열(28*28)의 이미지 포맷을 784의 1차원 배열로 변환
  tf.keras.layers.Dense(256, activation='relu'), # 256개의 노드(뉴런), relu 함수로 학습
  tf.keras.layers.Dropout(0.8), # 데이터를 80프로만 사용 => Drop out : 과적합을 방지하기 위하여 학습 단계마다 일부 뉴런을 제거
  tf.keras.layers.Dense(10, activation='softmax') # 10개의 확률 반환, 반환된 확률의 합이 1 
])

In [21]:
model.compile(optimizer='adam', # 경사 하강법 Adam : RMSProp + Momentum
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), # losses.SparseCategoricalCrossentropy :
                                                                                     #      레이블과 예측간의 교차 엔트로피 손실 계산
              metrics=['accuracy']) # 측정항목 = [정확성]

In [23]:
model.fit(x_train, y_train, epochs=5)# 훈련

Epoch 1/5


c:\users\rlaxo\appdata\local\programs\python\python36\lib\site-packages\keras\backend.py:4907: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  '"`sparse_categorical_crossentropy` received `from_logits=True`, but '


1875/1875 [==============================] - 4s 2ms/step - loss: 0.5405 - accuracy: 0.8346
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3494 - accuracy: 0.8952
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3112 - accuracy: 0.9066
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2828 - accuracy: 0.9165
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2720 - accuracy: 0.9180


In [24]:
model.evaluate(x_test,  y_test, verbose=2) # 검증

313/313 - 1s - loss: 0.1193 - accuracy: 0.9646


[0.11933445185422897, 0.9646000266075134]